### ISSUE TITLE
这是什么问题

### ISSUE THREAD

**Issue by isArtJay** [higker/sms_bomber#1]
![image](https://user-images.githubusercontent.com/48620527/101362680-66493880-38db-11eb-90a5-9957f1653395.png)

**Comment by higker** [comment]
1.你没有配置vscode环境
2.你没有导入包
3.你检查一下你的环境，你这个就是环境问题
4.https://www.liwenzhou.com/posts/Go/00_go_in_vscode/

**Comment by higker** [comment]
对最近这个项目使用的人多了，部分api接口好像有了限制不能正常调用，看自己运气。
